DROP TABLE IF EXISTS houses;
CREATE TABLE houses (
  id bigint generated by default as identity (start with 1),
  description VARCHAR(255) NOT NULL,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO houses (description, price) values ('some desc', 10.20);
INSERT INTO houses (description, price) values ('some other desc', 99.99);
